### ISSUE TITLE
标题栏右键菜单乱码

### ISSUE THREAD

**Issue by dmmocn** [quark-zju/FooNote#2]
系统是64位Win10，在标题栏上右键，菜单出现乱码
![Snipaste_2021-03-07_23-15-04](https://user-images.githubusercontent.com/35016284/110244760-4b9a6480-7f9b-11eb-95b8-d3d13b96ae5f.png)

**Comment by quark-zju** [comment]
谢谢报告，是编码使用的问题，新版本会修复，也可以选择“使用 UTF-8 提供全球语言支持“来解决：

![image](https://user-images.githubusercontent.com/445459/110248376-95486800-7f25-11eb-8885-0dcbfa25690d.png)

**Comment by dmmocn** [comment]
感谢~我好了_(:з」∠)_
