### ISSUE TITLE
再来汇报一个小bug，0.8.2选中挂载点或文件夹后，按回车键无法进入文本框

### ISSUE THREAD

**Issue by dmmocn** [quark-zju/FooNote#3]
再来汇报一个小bug，0.8.2选中挂载点或文件夹后，按回车键无法进入文本框，必须要用鼠标点一下文本框才能打字。。
这个真不能怪我太龟毛，只能说上一个版本的全程快捷键操作实在太香了，委实让我难以割舍→_→

**Comment by quark-zju** [comment]
这么细微的差别都被发现了，不行，我要重做 0.8.2（其实 0.8.2 还有一些别的问题）。

**Comment by dmmocn** [comment]
2333软件确实好用，你不说我都没发现有别的问题
特意测试了一下，还意外发现了新功能~
新功能倒是有点小问题，你可能已经知道了：
加密文件夹设密码按确定之后好像会卡住，还有临时文件夹如果复制粘贴到自己的子级别，好像会陷入无限循环展开层级
还有一个不算bug的，如果套了很多很多很多层文件夹，可能会需要一个横向的滚动条……不过这些都不影响使用基本功能，对我来说软件已经足够好用了，大佬请继续加油~

**Comment by quark-zju** [comment]
改好了。

> 加密文件夹设密码按确定之后好像会卡住

应该只有在其他挂载点内才会发生，所以一开始没有发现...

> 如果复制粘贴到自己的子级别，好像会陷入无限循环展开层级

这有什么问题吗？（笑

> 可能会需要一个横向的滚动条

试了一下，绘制拖拽预览时有点小麻烦，然后好像也不够简洁。于是做成选项了。

**Comment by dmmocn** [comment]
![1](https://user-images.githubusercontent.com/35016284/111016705-59604780-83ea-11eb-9a5d-c8892816e6fc.gif)
是遇到了这样的问题，但如果不复制粘贴，直接创建就没问题。也许就是这样的功能？我布吉岛，不会用= =
我是朋友推荐，好像他还在用bugoonote，不过我这边有输入法兼容的问题

**Comment by quark-zju** [comment]
是这样的，挂载点这个功能做出来的时候，就要有处理各种奇怪的情况的决心。比如同一个地址被多次挂载：

![foonote-mount](https://user-images.githubusercontent.com/445459/111017316-8ae3ff00-8367-11eb-960b-7013098a34c7.gif)

同步更新，编辑哪里都可以，因为都是同一个文件。

接受了同一地址在多出同步更新的设定后，再看无限循环是不是就有点道理了？尽管出现多次，因为是同一个文件，所以在哪里编辑内容都一样：

![image](https://user-images.githubusercontent.com/445459/111018314-00060300-836d-11eb-8f75-66585409a45f.png)

不一定要自成环，双文件也能成环：

![image](https://user-images.githubusercontent.com/445459/111018256-af8ea580-836c-11eb-9a9d-9db4fe6a18fd.png)

环是阻止不了的。为什么？因为 FooNote 无法监控并阻止所有成环的操作。比如你可以在 b 中挂载 c，这时候还没成环。然后把 FooNote 关掉，把 b 重命名为 c，那么 c 就自环了。FooNote 没法在关闭的情况下阻止文件重命名，这里的重命名会导致成环。同样的，如果挂载 Git 的话，如果用 Git 软件而非 FooNote 修改了 Git 上的内容，也可以造出一个环。

既然阻止不了环，那么就要支持。无差别对待，挂载地址相同就同步更新是目前的处理办法。

临时挂载点创建的时候会内部挑选一个独一无二的地址，地址在界面上是不显示的。复制粘贴的时候沿用相同地址的，就会造成环。

其实环本身没什么，只要搜索不要无限循环下去，保存不要把磁盘写满就可以了，而 FooNote 第一版就做到了这两点。

**Comment by dmmocn** [comment]
厉害了，原来挂载点还能这么用，涨姿势了~
大纲我用过父子关系式的，也用过集合式的，还是第一次知道连环式的都能搞，目瞪狗呆
妥了，我没问题了，感谢大佬的耐心解答~

**Comment by quark-zju** [comment]
再补充解释一下复制粘贴为什么会设计成这样。由于环不可避免，复制的时候不能做深复制（深复制就是无限展开，复制所有展开的内容），因为可以陷入无限多层。只能是做成浅复制（浅复制就是见到挂载点就停，只记录挂载点的地址，不会深入展开复制其下的内容）。浅复制更容易导致环的出现，但也避免了环的无限循环复制的问题。

临时挂载点的复制和创建是不同的操作，创建的时候的要求是创建一个新的空白的挂载点，所以要挑选一个内部还没有被使用的地址。复制则是要求按原样复制，你可以复制粘贴一个非空白的挂载点就能看出来区别了。

**Comment by dmmocn** [comment]
我是这么理解的，感觉虽然是对挂载点使用了复制，但其实是引用了同一个原文件，而不是创建一个与原文件无关的副本
所以如果原文件变化，复制出来的文件也会同步变化，环就是因为这种引用关系而产生的吧……
所以虽然看起来都复制，但其实这是两个功能，一种是复制，一种是关联复制
关联复制的优点是可以和原文件同步，缺点是可能会产生环，而普通复制的优点是不会产生环，但没办法同步更改
不知道理解得对不对

**Comment by quark-zju** [comment]
是。但不使用复制粘贴也能造成环，而且如果粘贴后挂载点从特殊图标变成普通文件夹图标也会显得奇怪。所以综合起来就采用目前的设计了。

**Comment by dmmocn** [comment]
这样挺好的，没啥问题233

**Comment by quark-zju** [comment]
最新的 v0.8.3 版本修改了临时笔记节点属性，现在和回收站一样不可复制，这个问题就现在关闭了。

PS: 我写了一个用户手册介绍了大部分"隐藏"功能，快捷键方面有一个 `Ctrl+/` 有时会有用。

**Comment by dmmocn** [comment]
好的~
ctrl+/好用~
手册很详细，尤其喜欢Scintilla~
右键菜单里的选项貌似增加了，现在【退出】的位置好像有点容易被误点到？
不知道挪到最下面会不会好一点，P了一下图，算是提供参考：
![Snipaste_2021-03-29_23-07-36](https://user-images.githubusercontent.com/35016284/112858038-11c50580-90e4-11eb-8ec3-168753a8d06a.png)
